//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.29 at 10:07:38 PM IST 
//


package springwebservice.example.com;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the springwebservice.example.com package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: springwebservice.example.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllHaiRequest }
     * 
     */
    public GetAllHaiRequest createGetAllHaiRequest() {
        return new GetAllHaiRequest();
    }

    /**
     * Create an instance of {@link GetHaiByIdRequest }
     * 
     */
    public GetHaiByIdRequest createGetHaiByIdRequest() {
        return new GetHaiByIdRequest();
    }

    /**
     * Create an instance of {@link GetHaiByIdResponse }
     * 
     */
    public GetHaiByIdResponse createGetHaiByIdResponse() {
        return new GetHaiByIdResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link Hai }
     * 
     */
    public Hai createHai() {
        return new Hai();
    }

    /**
     * Create an instance of {@link GetAllHaiResponse }
     * 
     */
    public GetAllHaiResponse createGetAllHaiResponse() {
        return new GetAllHaiResponse();
    }

    /**
     * Create an instance of {@link AddHaiResponse }
     * 
     */
    public AddHaiResponse createAddHaiResponse() {
        return new AddHaiResponse();
    }

    /**
     * Create an instance of {@link AddHaiRequest }
     * 
     */
    public AddHaiRequest createAddHaiRequest() {
        return new AddHaiRequest();
    }

}
